# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

call_rpart_ <- function(formula_obj, wrap_rpart, newdata, weight_vec, classname_map) {
    .Call('fastBoost_call_rpart_', PACKAGE = 'fastBoost', formula_obj, wrap_rpart, newdata, weight_vec, classname_map)
}

adaboost_main_loop_ <- function(formula_obj, data_df, nIter, wrap_rpart, vardep, classname_map, boost_method) {
    .Call('fastBoost_adaboost_main_loop_', PACKAGE = 'fastBoost', formula_obj, data_df, nIter, wrap_rpart, vardep, classname_map, boost_method)
}

calculate_test_error_ <- function(vardep, predicted_class_int) {
    .Call('fastBoost_calculate_test_error_', PACKAGE = 'fastBoost', vardep, predicted_class_int)
}

predict_adaboost_ <- function(tree_list, coeff_vector, newdata, num_examples, wrap_rpart_predict, classnames_map) {
    .Call('fastBoost_predict_adaboost_', PACKAGE = 'fastBoost', tree_list, coeff_vector, newdata, num_examples, wrap_rpart_predict, classnames_map)
}

