# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastboost_rpart_test_ <- function(x, call_rpart) {
    .Call('fastBoost_fastboost_rpart_test_', PACKAGE = 'fastBoost', x, call_rpart)
}

call_rpart_ <- function(wrap_rpart, newdata, weight_vec) {
    .Call('fastBoost_call_rpart_', PACKAGE = 'fastBoost', wrap_rpart, newdata, weight_vec)
}

