# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastboost_rpart_test_ <- function(x, call_rpart) {
    .Call('fastBoost_fastboost_rpart_test_', PACKAGE = 'fastBoost', x, call_rpart)
}

call_rpart_ <- function(wrap_rpart, newdata, weight_vec) {
    .Call('fastBoost_call_rpart_', PACKAGE = 'fastBoost', wrap_rpart, newdata, weight_vec)
}

adaboost_main_loop_ <- function(formula_char, data_df, nIter, wrap_rpart) {
    .Call('fastBoost_adaboost_main_loop_', PACKAGE = 'fastBoost', formula_char, data_df, nIter, wrap_rpart)
}

predict_adaboost_ <- function(tree_list, coeff_vector, newdata, num_examples, wrap_rpart_predict) {
    .Call('fastBoost_predict_adaboost_', PACKAGE = 'fastBoost', tree_list, coeff_vector, newdata, num_examples, wrap_rpart_predict)
}

real_adaboost_main_ <- function(formula_char, data_df, vardep, nIter, wrap_rpart) {
    .Call('fastBoost_real_adaboost_main_', PACKAGE = 'fastBoost', formula_char, data_df, vardep, nIter, wrap_rpart)
}

